name: Build EXE with Nuitka

on:
  push:
    branches: [scum]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Nuitka
      run: pip install nuitka

    - name: Build EXE
      run: |
        python -m nuitka --standalone --onefile scum.py

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: compiled-exe
        path: scum.exe
